FROM jenkins/jenkins:lts

USER root

# Instala Maven e curl (Docker CLI não é necessário com DinD)
RUN apt-get update && \
    apt-get install -y maven curl && \
    apt-get clean

# Instala Docker Compose (v2.x)
RUN curl -SL https://github.com/docker/compose/releases/download/v2.24.4/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose

USER jenkins