FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y docker.io maven && \
    groupadd docker || true && \
    usermod -aG docker jenkins && \
    apt-get clean

USER jenkins