

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: cadastro_cliente
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    networks:
      - empresa-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - empresa-net

  cadastro-cliente:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadastro-cliente
    ports:
      - "8082:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - empresa-net

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile-Jenkisfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - empresa-net

volumes:
  jenkins_home:

networks:
  empresa-net:
    driver: bridge