FROM jenkins/jenkins:lts

USER root

# Instala Docker CLI e Maven
RUN apt-get update && \
    apt-get install -y docker.io maven curl && \
    groupadd docker || true && \
    usermod -aG docker jenkins && \
    apt-get clean

# Instala Docker Compose (v2.x)
RUN curl -SL https://github.com/docker/compose/releases/download/v2.24.4/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose

USER jenkins