spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  config:
    import:
      optional:configserver:

  application:
    name: cadastro-cliente

  datasource:
    url: jdbc:postgresql://postgres:5432/cadastro_cliente
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  cloud:
    config:
      enabled: false
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.amqp: DEBUG